### ISSUE TITLE
Let's make it cross-platform.

### ISSUE THREAD

**Issue by bundle555** [garvit-joshi/Password-Store#7]

**Comment by garvit-joshi** [comment]
Yes, Let's Do it, it would be a challenge for us. Can I ping you somewhere possibly Instagram, Twitter, or Facebook, that I would like to talk about some details?

**Comment by bundle555** [comment]
I'm on twitter https://twitter.com/m_ghost_rider
Thanks for support.

**Comment by garvit-joshi** [comment]
Hey @bundle555 I can't message you on twitter due to your privacy settings, could you please ming messaging me. 
https://twitter.com/garvit__joshi, here's my account

**Comment by garvit-joshi** [comment]
A cross-platform C++ Application will be made in another Repo, [@Redux](https://github.com/garvit-joshi/Redux)
